// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// addonDao is the data access object for the table xy_addon.
// You can define custom methods on it to extend its functionality as needed.
type addonDao struct {
	*internal.AddonDao
}

var (
	// Addon is a globally accessible object for table xy_addon operations.
	Addon = addonDao{internal.NewAddonDao()}
)

// Add your custom methods and functionality below.
