// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// smsTemplateDao is the data access object for the table xy_sms_template.
type smsTemplateDao struct {
	*internal.SmsTemplateDao
}

var (
	// SmsTemplate is a globally accessible object for table xy_sms_template operations.
	SmsTemplate = smsTemplateDao{internal.NewSmsTemplateDao()}
)
