// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// smsLogDao is the data access object for the table xy_sms_log.
type smsLogDao struct {
	*internal.SmsLogDao
}

var (
	// SmsLog is a globally accessible object for table xy_sms_log operations.
	SmsLog = smsLogDao{internal.NewSmsLogDao()}
)
