// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// smsVariableDao is the data access object for the table xy_sms_variable.
type smsVariableDao struct {
	*internal.SmsVariableDao
}

var (
	// SmsVariable is a globally accessible object for table xy_sms_variable operations.
	SmsVariable = smsVariableDao{internal.NewSmsVariableDao()}
)
